default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.dig(:database, :rta_username) %>
  password: <%= Rails.application.credentials.dig(:database, :rta_password) %>  
  database: <%= Rails.application.credentials.dig(:database, :rta_db) %>
  host: localhost

development:
  <<: *default

production:
  <<: *default
